import "./globals.css";
import NavBar from "@/components/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full m-0 p-0 overflow-hidden">
        <NavBar className="fixed top-0 left-0 w-full z-50" />
      
        <div className="relative w-screen h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}